### ISSUE TITLE
Is the complemented annotation used for the visual detection performance on the DAIR-V2X dataset in the paper？

### ISSUE THREAD

**Issue by wangsh2001** [yifanlu0227/HEAL#1]
Hi~
Congratulations on this work being accepted by ICLR， thank you for providing a complete collaboration perception framework.
I noticed that the default label value read by DAIR-V2X in image mode is cav_content['params']['vehicles_front']. Is the complemented annotation used for the visual detection performance on the DAIR-V2X dataset in the paper？
![image](https://github.com/yifanlu0227/HEAL/assets/118430859/3e7453d6-afe3-42da-94df-02c9e4fc9d7f)

**Comment by yifanlu0227** [comment]
No. It is the original label since there is only one front camera in DAIR-V2X dataset

**Comment by yifanlu0227** [comment]
camera based detection should use `cav_content['params']['vehicles_front']`, while LiDAR-based detection should use `cav_content['params']['vehicles_all']`,

**Comment by wangsh2001** [comment]
okay, thanks~
