### ISSUE TITLE
About aligners

### ISSUE THREAD

**Issue by xhjy2020** [yifanlu0227/HEAL#12]
Hi, yifan.
I noticed that the encoder in your code consists of three parts: encoder, backbone and aligner. The aligner does not seem to change the dimension of the feature map.
So, what is its role in local training? Is it just used to increase the number of trainable parameters? Would removing it and just changing the encoder and bakbone parameters make a big difference to the alignment?
Looking forward to your reply!

**Comment by yifanlu0227** [comment]
No. Due to some of my previous setups, I put an aligner here. In the current framework, it is just a trainable network (added some network parameters, modified the number of channels for some feature maps, not necessary). You can remove it alive to set it to nn.identity

**Comment by xhjy2020** [comment]
I understand, thank you very much!
