### ISSUE TITLE
How the camera features of different cars are transferred to the ego's bev?

### ISSUE THREAD

**Issue by nxdxml** [yifanlu0227/HEAL#13]
![heatmap](https://github.com/yifanlu0227/HEAL/assets/67680320/efe532de-78a6-4499-9a75-0bb68ea10c56)
I visualized the input camera features and could not find how the features were transferred under the ego's bev.
encoding method：LSS

**Comment by yifanlu0227** [comment]
Hi! The warping is implemented in function `warp_affine_simple`

For example, you can see the Pyramid Fusion calls `warp_affine_simple` in [here](https://github.com/yifanlu0227/HEAL/blob/4882bd02514725fa5e2e5717d410de739f33790e/opencood/models/fuse_modules/pyramid_fuse.py#L17)

For other fusion methods, you can find we are doing the similar things, just call `warp_affine_simple`!

**Comment by nxdxml** [comment]
Thanks for the answer!

**Comment by yifanlu0227** [comment]
Hey, and I have a wonderful illustration for the `warp_affine_simple` function:
<img width="381" alt="Screenshot 2024-05-14 at 13 47 56" src="https://github.com/yifanlu0227/HEAL/assets/45688237/c681966d-5e18-4247-a49f-12b10c6cb176">
<img width="852" alt="Screenshot 2024-05-14 at 13 48 01" src="https://github.com/yifanlu0227/HEAL/assets/45688237/06f8f261-8f03-473e-a239-5b171856389a">

**Comment by xhjy2020** [comment]
Hello, yifan. 
Can you tell me the source of this picture? Thanks~

**Comment by yifanlu0227** [comment]
It is written by myself, not published :)

**Comment by xhjy2020** [comment]
Haha, oky, thanks~
