### ISSUE TITLE
Late_Fusion checkpoint加载报错：尺寸不匹配

### ISSUE THREAD

**Issue by Wyatt2021** [yifanlu0227/HEAL#14]
在尝试加载`Late_Fusion.zip`中的checkpoint时遇到了问题。错误表明`HeterModelLate`的`encoder_m3.spconv_block.conv_input.0.weight`层的权重形状与checkpoint中的不匹配。  

错误信息如下：
RuntimeError: Error(s) in loading state_dict for HeterModelLate:
        size mismatch for encoder_m3.spconv_block.conv_input.0.weight: copying a param with shape torch.Size([3, 3, 3, 64, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 64]).

在loading checkpoint的时候也会报错：
------ Loading Checkpoint ------
Missing keys from ckpt:

Extra keys from ckpt:
encoder_m4

encoder_m4.camencode.up1.conv.4.bias
encoder_m4.camencode.up1.conv.1.running_var
encoder_m4.camencode.up1.conv.4.num_batches_tracked
encoder_m4.camencode.up1.conv.1.num_batches_tracked
encoder_m4.camencode.up1.conv.0.weight
encoder_m4.camencode.up2.conv.4.bias
encoder_m4.camencode.up2.conv.4.running_var
encoder_m4.camencode.up2.conv.1.num_batches_tracked
encoder_m4.camencode.up2.conv.4.num_batches_tracked
encoder_m4.camencode.up1.conv.4.running_var
encoder_m4.camencode.up1.conv.1.bias
encoder_m4.camencode.up1.conv.1.weight
encoder_m4.camencode.up2.conv.1.weight
encoder_m4.camencode.up2.conv.4.weight
encoder_m4.camencode.up2.conv.1.bias
encoder_m4.camencode.up2.conv.1.running_mean
encoder_m4.camencode.up2.conv.4.running_mean
encoder_m4.camencode.up1.conv.1.running_mean
encoder_m4.camencode.up2.conv.1.running_var
encoder_m4.camencode.up2.conv.0.weight
encoder_m4.camencode.up1.conv.4.weight
encoder_m4.camencode.up1.conv.4.running_mean
encoder_m4.camencode.up2.conv.3.weight
encoder_m4.camencode.up1.conv.3.weight

**Comment by yifanlu0227** [comment]
We use spconv 1.2.1 for training, and the checkpoint file is incompatible with spconv 2.x.

And [this issue](https://github.com/yifanlu0227/HEAL/issues/6#issuecomment-2008567672) also comments on some incompatibility with spconv 2.x training, so using spconv 1.2.1 is suggested.
