### ISSUE TITLE
 How to solve the `too many cavs reinitialize` problem? Just delete it?

### ISSUE THREAD

**Issue by Chinese-Coding** [yifanlu0227/HEAL#17]
# `too many cavs reinitialize`

## Chinese
当我第一次按照您提供的README中执行本程序时, 在控制台出现了这样一行输出 `too many cavs reinitialize`, 并伴随着一些 errors. 我第一次时直接将那些不符合条件的时间戳的文件夹给移走了, 例如: `dataset/OPV2V/train/2021_09_09_22_21_11` 这个文件夹, 它里面总共有 6 辆车 (Figure 1). 
当我今天下载好 `OPV2V-H` 数据集时, 我发现 `OPV2V-H` 数据集中保留了这些文件, 并做了相应的处理 (顺便提一嘴, 我发现了 `OPV2V-H` 有国内的[镜像](https://gitee.com/hf-datasets/OPV2V-H), 就是下载速度有些慢, 平均 3M/s, 我没有测试过直接下载的情况, 自我感觉良好). 所以, 总感觉有些不妥当, 想问一下大家是怎么解决的.

为了提高代码的鲁棒性, 我还在输出 `too many cavs reinitialize` 的地方添加了如下的代码 (Figure 2)
## English
When I first executed this program according to the README you provided, a line of output `too many cavs reinitialize` appeared in the console, accompanied by some errors. The first time I directly moved the folders with timestamps that did not meet the conditions, for example: the folder `dataset/OPV2V/train/2021_09_09_22_21_11`, which has a total of 6 vehicles (Figure 1). 

When I downloaded the `OPV2V-H` dataset today, I found that these files were retained in the `OPV2V-H` dataset and processed them accordingly (by the way, I found that `OPV2V-H` has a domestic [mirror](https://gitee.com/hf-datasets/OPV2V-H), but the download speed is a bit slow, averaging 3M/s. I haven't tested the direct download situation, but I feel good about it). So, I always feel that something is wrong, and I want to ask how everyone solves it.

In order to improve the robustness of the code, I also added the following code where `too many cavs reinitialize` is output (Figure 2)

## Figure
![image](https://github.com/yifanlu0227/HEAL/assets/137599793/823dc0fc-bd59-4b3c-b311-1b6f8affd107)
<p style="text-align: center;"><em>Figure 1: There 6 cavs in `dataset/OPV2V/train/2021_09_09_22_21_11`</em></p>

![image](https://github.com/yifanlu0227/HEAL/assets/137599793/11a63214-b5e6-427f-8f8f-4f634eac555f)
<p style="text-align: center;"><em>Figure 2</em></p>

```python
warnings.warn(f'In {scenario_folder}, there are too many cavs reinitialize, '
                                  f'Please check the data set to avoid errors')
```

**Comment by yifanlu0227** [comment]
Hi, 这个没有关系。

在yaml里的`train_params.max_cav`可以控制场景里最多的agent数量。这个通常被设置成5，如果数据集里一个scene 的agent数量大于5，它就会break，控制读取的agent数量为5。你可以忽略这个warning。
