### ISSUE TITLE
How to get depth image in v2xset data set?

### ISSUE THREAD

**Issue by deyang2000** [yifanlu0227/HEAL#2]
Hi, there!
I'm using your brilliant work, but I'm having some problems. 

When I used  **python opencood/tools/train.py -y opencood/hypes_yaml/v2xset/CameraOnly/camera_pyramid.yaml**

Error occurred:
**FileNotFoundError: [Errno 2] No such file or directory: '/data/v2xset/train/2021_09_09_19_27_35/15009/001925_depth0.png'**

I looked up the data format description of V2XSet:

V2XSet
├── train # data for training
│   ├── 2021_08_22_21_41_24  # scenario folder
│     ├── data_protocol.yaml # the simulation parameters used to collect the data in Carla
│     └──  -1 # The infra's id 
│       └── 00000.pcd - 00700.pcd # the point clouds data from timestamp 0 to 700
│       ├── 00000.yaml - 00700.yaml # corresponding metadata for each timestamp
│       ├── 00000_camera0.png - 00700_camera0.png # frontal camera images
│       ├── 00000_camera1.png - 00700_camera1.png # right rear camera images
│       ├── 00000_camera2.png - 00700_camera2.png # left rear camera images
│       └── 00000_camera3.png - 00700_camera3.png # back camera images
|      └──  112 # The connected vehicle id
├── validate  
├── test

There is no depth picture in the v2xset data set I downloaded. How did you get such picture?

I would appreciate it very much if you could reply as soon as possible.

**Comment by yifanlu0227** [comment]
Hi, we do not generate V2XSet's depth data and it's a mistake in the config writing.

I've removed the depth items in `opencood/hypes_yaml/v2xset/CameraOnly/camera_pyramid.yaml`. Thanks for pointing it out!

**Comment by deyang2000** [comment]
Hello! I also found a mistake.
The specific location is **HEAL-main/opencood/hypes_yaml/v2xset/CameraOnly/camera_coalign.yaml**  lines 139 and 140.
![image](https://github.com/yifanlu0227/HEAL/assets/129513825/546c42d8-9bcf-48ec-889b-3a98456af56c)
Should be changed to:
![image](https://github.com/yifanlu0227/HEAL/assets/129513825/a99f8782-3e84-442a-bebe-7c731c00e5ee)
Then I can run it successfully!

**Comment by yifanlu0227** [comment]
Thanks for your careful revision!
