### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by gezi0917** [yifanlu0227/HEAL#28]
请问代码中是否实现将dair_v2x数据集400通道转为40通道？

**Comment by yifanlu0227** [comment]
您是说lidar数据么，我们没有做额外的处理，就是用数据集提供的lidar

**Comment by gezi0917** [comment]
感谢您的回复，我这里是想问  tabel3的这一部分结果，LP(40),是吧400线转为40线吗？：
![微信图片_20241011173117](https://github.com/user-attachments/assets/0ffa0f70-f9fc-4187-9c39-c0550d9240bc)

**Comment by yifanlu0227** [comment]
此处为笔误哈，没有对DAIR-V2X的数据进行更改

**Comment by gezi0917** [comment]
好的（不好意思我上面也笔误是300线不是400），还有一个问题想请教，在我上方截图的那组实验中，heal的第一阶段要训练一个基本的同构网络，但dair_v2x数据集只有两个agent，第一阶段是把车和基础设施都拿过来训练整体pointpillar，然后第二阶段仍然用这个车端数据训练新的encoder second吗

**Comment by yifanlu0227** [comment]
对

**Comment by gezi0917** [comment]
> 对

非常感谢~
