### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by gezi0917** [yifanlu0227/HEAL#29]
您好，我下载了您的dair_v2x数据集补充注释，并且按照heal方法进行了stage1的训练，采用的是lidar_based，直接运行您的代码，python opencood/tools/train.py -y None --model_dir opencood/logs/HEAL_m1_based/stage1/m1_base ，得到的同构结果bestval_epoch19是AP30:  0.80,  AP50:   0.76，AP70:  0.59   与table5中效果有一定差距，请问是否需要一些其他的配置，或是训练细节？
![tabel5](https://github.com/user-attachments/assets/65293554-c676-46ac-847f-097ea9f5beac)

**Comment by gezi0917** [comment]
我使用/space0/guog/projects/HEAL/opencood/hypes_yaml/dairv2x/MoreModality/HEAL/stage1/m1_pyramid.yaml进行训练，/space0/guog/projects/HEAL/opencood/tools/inference.py 进行推断。

**Comment by ChengChen2020** [comment]
您好，我也得到了类似的结果，请问您是如何解决的？

**Comment by wjwless** [comment]
您好，我想知道数据集如何设置的呀，为什么我的数据集一直找不到路径，如果有机会看到您的数据集格式以及路径参考，感激不尽

**Comment by ysy200187** [comment]
> 您好，我想知道数据集如何设置的呀，为什么我的数据集一直找不到路径，如果有机会看到您的数据集格式以及路径参考，感激不尽

请问你解决了吗
