### ISSUE TITLE
Question about "assignment_path"

### ISSUE THREAD

**Issue by deyang2000** [yifanlu0227/HEAL#3]
Hi ,  there! I had a problem when using **dairv2x** related files. These yaml files have **assignment_path: None**，when I try to use

**python opencood/tools/train.py -y opencood/hypes_yaml/dairv2x/CameraOnly/camera_coalign.yaml**

An error has been reported:

Dataset Building
/data/cooperative-vehicle-infrastructure/train.json
/data/cooperative-vehicle-infrastructure/cooperative/data_info.json
None
Traceback (most recent call last):
  File "opencood/tools/train.py", line 189, in <module>
    main()
  File "opencood/tools/train.py", line 37, in main
    opencood_train_dataset = build_dataset(hypes, visualize=False, train=True)
  File "/home/liyf/HEAL-main/opencood/data_utils/datasets/__init__.py", line 27, in build_dataset
    dataset = fusion_dataset_func(base_dataset_cls)(
  File "/home/liyf/HEAL-main/opencood/data_utils/datasets/intermediate_heter_fusion_dataset.py", line 63, in __init__
    else read_json(params['heter']['assignment_path'])
  File "/home/liyf/HEAL-main/opencood/utils/common_utils.py", line 100, in read_json
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'None'

I think it is caused by the above reasons. I checked the yaml file for the V2Xset dataset and it has：

**assignment_path: "opencood/logs/heter_modality_assign/v2xset_4modality.json"** 

How to solve this problem, thank you very much!

**Comment by yifanlu0227** [comment]
DAIR-V2X does not need a modality assignment_file. It is typically specified in its dataset code.

Thus, I just use other dataset's assignment file (for example, v2xset_4modality.json) as a placeholder for this term when I train the models.

But it is misleading, so I change it to 'none' when releasing the code.  I have to admit that this part of the code has not been tested yet, I will correct the code as soon as possible. And for now, you can fill in the assignment_path with another dataset's json file like I did before. It would not be actually used for DAIR-V2X dataset.

**Comment by yifanlu0227** [comment]
Okay, I think it should be `assignment_path: null`. 

`assignment_path: None` will be interpreted as string by Pyyaml.

**Comment by deyang2000** [comment]
Thank you for your timely feedback. Wish you all the best！
