### ISSUE TITLE
Unable to get GT Bboxes from Infrastructure in V2XSET

### ISSUE THREAD

**Issue by creativevisionarydeveloper2024** [yifanlu0227/HEAL#30]
Thank you very much for your excellent work.

While working with the V2XSET dataset, I encountered an issue where the visualization of prediction results during inference did not include the gt boxes from the infrastructure. Upon printing the object_bbx_mask (as shown in the image below), I found that its value was 0 in certain scenes.
I would greatly appreciate your assistance in clarifying whether this might be a bug in the dataset reading part of the code or if it could be related to my usage of the dataset.

![990e97edf50b3f9e496ce5e5c432779](https://github.com/user-attachments/assets/67fb0ca0-d5d5-4900-98c5-7d48c984d2b9)
![bcff37ea4978214245ad931f4a83259](https://github.com/user-attachments/assets/bc3ec18a-746c-4752-b2e6-aca4d7cc56df)
![a0b88889dfdab8252b3a9692d1ed5d7](https://github.com/user-attachments/assets/a7e815a5-c003-4cc3-84d2-f465e826fa08)

**Comment by yifanlu0227** [comment]
Mainly due to `cav_lidar_range: &cav_lidar [-102.4, -102.4, -3, 102.4, 102.4, 1]`

The z-axis is insufficient to include the infra side's GT box, so they are filtered out.

**Comment by creativevisionarydeveloper2024** [comment]
> Mainly due to `cav_lidar_range: &cav_lidar [-102.4, -102.4, -3, 102.4, 102.4, 1]`
> 
> The z-axis is insufficient to include the infra side's GT box, so they are filtered out.

Thank you for your clarification. May I ask what range you would recommend for the Z-axis in V2XSET? For example, would z -> [-5, +3] be appropriate?

**Comment by yifanlu0227** [comment]
Sorry for the late reply. You can turn on the `enlarge_z` for `generate_object_center` in `opencood/data_utils/post_processor/base_postprocessor.py` to fetch the bounding boxes that is outside the `cav_lidar_range`. Since the RSU's LiDAR is set high from the ground, they are possibly filtered out in the `project_world_objects` step

https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/data_utils/post_processor/base_postprocessor.py#L202-L205

https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/utils/box_utils.py#L451-L456

**Comment by creativevisionarydeveloper2024** [comment]
> Sorry for the late reply. You can turn on the `enlarge_z` for `generate_object_center` in `opencood/data_utils/post_processor/base_postprocessor.py` to fetch the bounding boxes that is outside the `cav_lidar_range`. Since the RSU's LiDAR is set high from the ground, they are possibly filtered out in the `project_world_objects` step
> 
> https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/data_utils/post_processor/base_postprocessor.py#L202-L205
> 
> https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/utils/box_utils.py#L451-L456

Thanks

**Comment by creativevisionarydeveloper2024** [comment]
> Sorry for the late reply. You can turn on the `enlarge_z` for `generate_object_center` in `opencood/data_utils/post_processor/base_postprocessor.py` to fetch the bounding boxes that is outside the `cav_lidar_range`. Since the RSU's LiDAR is set high from the ground, they are possibly filtered out in the `project_world_objects` step
> 
> https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/data_utils/post_processor/base_postprocessor.py#L202-L205
> 
> https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/utils/box_utils.py#L451-L456

Thank you for your detailed response, much appreciated.

When I enable enlarge_z, there are no issues during training, and the ground truth (GT) bounding boxes from infra are not filtered out.
However, during testing, two parts of the post-processing code cause the predicted values and ground truth to be filtered out.
https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/data_utils/post_processor/voxel_postprocessor.py#L376
https://github.com/yifanlu0227/HEAL/blob/3b23fc7c020fd8fea1deff6ec92faedb26dcb365/opencood/data_utils/post_processor/voxel_postprocessor.py#L394-L399
Would it be possible to directly set the lidar_range and gt_range to [-102.4, -102.4, -5, 102.4, 102.4, 3] in the config, expanding the range of the z-axis to resolve this issue? This way, there would be no need for excessive code modifications.

I look forward to receiving your response soon.
