### ISSUE TITLE
论文中实验结果

### ISSUE THREAD

**Issue by guoge0322** [yifanlu0227/HEAL#34]
很感谢您的优秀工作，您这个表中的数据推理方式，是每种agent依次累计添加进去的还是单独添加进去的？如果是后者，推理用的json仍然是您给的opv2v_4modality_in_order.json吗？比如当只有Lp64和Ls32时，如何分配进行推理得到的ap50: 0.892 ?
![image](https://github.com/user-attachments/assets/f09435c4-cc49-4080-853b-e78f5b4dc897)

**Comment by gezi0917** [comment]
已解决
