### ISSUE TITLE
关于论文中表2

### ISSUE THREAD

**Issue by gezi0917** [yifanlu0227/HEAL#35]
非常感谢您的出色工作，您在这个表中的数据推理方式，是多个代理依次累加的还是单独添加的？如果是后者，推理用的 json 仍然是您给出的 opv2v_4modality_in_order.json，或许应该给出您在推理只有某两种agent是用到的mapping_dict。比如说当只有Lp64和Ls32时，如何分配进行推理得到的ap50: 0.892 ?
![image](https://github.com/user-attachments/assets/03379ed1-111d-47c3-a581-fa2e836cd4d6)

**Comment by yifanlu0227** [comment]
你好，这里一个modality会对应一辆车，依次加入到场景里。加到最后场景里会有L64 + C384 + L32 + C336这样四辆车，对应这里的最后一列。因此从左到右AP没有下降，因为参与的协作者增加了。

测试时agent会按照下面的方式分配每个模态。会存在一些scene的agent数量少于4，比如3，那就只会加到L64 + C384 + L32
https://github.com/yifanlu0227/HEAL/blob/main/opencood/modality_assign/opv2v_4modality_in_order.json

**Comment by gezi0917** [comment]
> 你好，这里一个modality会对应一辆车，依次加入到场景里。加到最后场景里会有L64 + C384 + L32 + C336这样四辆车，对应这里的最后一列。因此从左到右AP没有下降，因为参与的协作者增加了。
> 
> 测试时agent会按照下面的方式分配每个模态。会存在一些scene的agent数量少于4，比如3，那就只会加到L64 + C384 + L32 https://github.com/yifanlu0227/HEAL/blob/main/opencood/modality_assign/opv2v_4modality_in_order.json

感谢您的回复！
