### ISSUE TITLE
About DAIR-V2X dataset

### ISSUE THREAD

**Issue by EdenGabriel** [yifanlu0227/HEAL#36]
Hi, thanks for your meaningful work.
When i download the DAIR-V2X-C dataset, i get five files: 
> cooperative-vehicle-infrastructure
cooperative-vehicle-infrastructure-infrastructure-side-image
cooperative-vehicle-infrastructure-infrastructure-side-velodyne
cooperative-vehicle-infrastructure-vehicle-side-image
cooperative-vehicle-infrastructure-vehicle-side-velodyne

so, should i merge cooperative-vehicle-infrastructure-infrastructure-side-image and cooperative-vehicle-infrastructure-infrastructure-side-velodyne as the v2x-i ? merge vehicle-side-image and vehicle-side-velodyne as v2x-v? and rename cooperative-vehicle-infrastructure as v2x-c？ right? 
Thanks,

**Comment by EdenGabriel** [comment]
i fix it. thanks.

**Comment by yaoyaoling123** [comment]
May I ask how you managed to handle it? This is very important to me. Thank you！
