### ISSUE TITLE
What's the meaning of v2xset_4modality.json?

### ISSUE THREAD

**Issue by deyang2000** [yifanlu0227/HEAL#4]
Hello, yifan. 
I trained directly with the original v2xset data set, and everything worked fine.
Now, I have made some modifications to the original data set v2xset. Specifically, I have redistributed the files in the original training, verification, and test sets to get a new data set. (Equivalent to only changing the file path)
There are some errors when I train with the new data set, which is related to the v2xset_4modality.json file.

I noticed that in the camera pyramid.yaml file
![image](https://github.com/yifanlu0227/HEAL/assets/129513825/da7d48ce-55ef-4e3b-a1b0-4981aca8b295)
ego is set to m2, which should be the error caused here.
What rules are used to assign m1/m2/m3/m4 in the v2xset_4modality.json file? How do I make changes based on my new data set?
I would appreciate your prompt reply.

**Comment by deyang2000** [comment]
Specifically, my new dataset looks like this:
Total scenes: 58
29 contain roadside facilities.
The data set is divided into:
Train_vehicle:training dataset for vehicle .(29)
Val_vehicle:validate dataset for vehicle .(29)
New_scene: New scenes including V2I,which is the same as Val_vehicle.(29)

**Comment by deyang2000** [comment]
I have identified the problem and am now training the model, hoping that this new data set will be helpful for my further research.

**Comment by yifanlu0227** [comment]
I am glad the problem has been solved. 

- The identifiers like `m1, m2` in `v2xset_4modality.json` are used to assign agent type to each agent in the scene. With this assignment, we ensure the validation scenarios for all methods are consistent and fixed.

- The identifiers like `m1, m2` in `${METHOD}.yaml` are used to specify the sensor configuration and detection model used by this agent type (like `m2` in the case of `camera_pyramid.yaml`). 

In `${METHOD}.yaml`, there is also a concept of `mapping_dict`. It maps the given agent type of `v2xset_4modality.json` to the agent type in the current experiment. As you can see, `camera_pyramid.yaml` is a homogeneous collaborative perception setting, so the type of all agents should be the same, which can be referred to by `m2`.

Just note that `mapping_dict` will not take effect during the training process to introduce more data augmentation. Each agent will be randomly assigned an agent type that exists in yaml.

**Comment by deyang2000** [comment]
Thank you very much for your answer!
So can I take it this way:
There is a folder named **"2021_08_18_21_38_28"** in v2x_train, and the subfolders of **"2021_08_18_21_38_28"** are not assigned to m2 in **V2Xset_4modalm. json**. So **"2021_08_18_21_38_28"** is not used as training data actually.


    "2021_08_18_21_38_28": {
        "8786": "m3",
        "8795": "m4"
    }

**Comment by deyang2000** [comment]
Oooooh, I misunderstood. Thank you.
